<?php

/**
 * @file
 * This file contains theme suggestions.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function odd_admin_theme_suggestions_form_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function odd_admin_theme_suggestions_block_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function odd_admin_theme_suggestions_links__toolbar_shortcuts_alter(array &$suggestions, array $variables) {

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function odd_admin_theme_suggestions_menu_alter(array &$suggestions, array $variables) {

}
